### ISSUE TITLE
Any way to initialize server with whole planet data at once?

### ISSUE THREAD

**Issue by kunokdev** [ddmng/nominatim-local-server#1]
Is there option to initially start with whole planet data? 
Have you tested and would you share your experience with the hardware requirements for server setup?

**Comment by ddmng** [comment]
For starting with whole world data you should at least
>  Modify Dockerfile, set your url for PBF
>  `ENV PBF_DATA http://download.geofabrik.de/europe/italy-latest.osm.pbf`
changing the URL so that it points to the whole world file, like:

https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/pbf/planet-170717.osm.pbf

About performance, I remember that on a VM with 4 processors and 8 GB of RAM it took hours for the first setup (it has to build the internal GIS database) but then, queries for a single user were very fast (under 2 secs most of them). Consider that the server was already running other stuff and I was not looking for a performance estimation but I only wanted to know if it worked, so that one day we could have used it.

Have you already tried to start it up?

**Comment by kunokdev** [comment]
I am still considering options. I am gathering free space on our servers so I am trying to explore what is possible and how much hardware should I free for this task. Just installed Ubuntu 14.04 on a local machine, I am going to build it tomorrow morning with sample data. Gotta see if it works out for me. Otherwise I will use SaaS from LocationIQ or Google APIs for my reverse geocoding needs. 
By the way, which type of storage disks did you use? And did you use whole planet or just parts?
Thanks for quick reply.

**Comment by ddmng** [comment]
I used spinning disks but, I repeat, I was not looking for performance at that time. And I loaded only the Italy file. If you want to load all the world, then I think you'll have to wait a lot of hours at the first run and I don't know how fast it will go at the end. The only way to know it is try.

I did't know LocationIQ and it's good to know about it. In my use case, I would move to a SaaS only if it would give me more precision. There are entire towns in Italy whose names are still not present on Openstreetmap, so consider it when choosing an online service. I remember I found time ago a sort of statistics for OSM coverage but I can't  find it right now.

**Comment by kunokdev** [comment]
I also want to mention that LocationIQ is very flexible with their offering. They even provide custom services for low budget. In my case I only need huge amount of requests for initial data fetch (because I use reverse geocoding for data cleaning/formatting) and maybe even free plan would be enough to cover new/updated data each week.
However, I am going to try to install Nominatim local instance anyway. I don't mind waiting few days for the build as long as ending result will be able to host server that providers reverse geocoding at acceptable response speed and covers whole globle. :)

**Comment by ddmng** [comment]
Hi, have you had success building the whole globe? In the next weeks I think I'll have to make some progress on this project to better test the local server solution. LocationIQ is interesting and I think I'll ask them if they have an offline solution, like a VM or docker image ready-to-use in a offline environment.

**Comment by kunokdev** [comment]
@ddmng At the end I had to give up. Had issues due to lack of hardware (at the end I had even less hardware than I thought, because I had to add more new scripts to the server), decided to buy data from locationIQ at the end. 
As for offline, they have something. 
They provide self-hosted service. More details in this attachment (link from their website) - https://view.attach.io/ryiFAKzmb
